/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const Group = t.iface([], {
  "id": "string",
  "name": "string",
  "mnemonic": "string",
});

export const ItemGroup = t.iface(["Group"], {
  "groupId": "string",
});

export const Settings = t.iface([], {
  "alertThresholds": "any",
  "itemWidthPx": "number",
  "itemHeightPx": "number",
  "itemSpacingPx": "number",
  "itemHorizontalSpacingPx": "number",
  "counterFontSizePx": "number",
  "itemFontSizePx": "number",
  "groupFontSizePx": "number",
});

export const Workstate = t.iface([], {
  "itemCounts": "any",
  "groupCounts": "any",
});

export const Session = t.iface([], {
  "name": "string",
  "groups": t.array("Group"),
  "itemGroups": t.array("ItemGroup"),
  "settings": "Settings",
  "workstate": "Workstate",
});

const exportedTypeSuite: t.ITypeSuite = {
  Group,
  ItemGroup,
  Settings,
  Workstate,
  Session,
};
export default exportedTypeSuite;
